---
title: "HomeWork_2"
author: "Ekaterina Fokina"
date: "2022-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Загрузим данные и необходимые пакеты (№1)

```{r, message=FALSE, warning=FALSE}
insurance <- read.csv("insurance_cost.csv")
str(insurance)

library(dplyr)
library(ggplot2)
library(plotly)
library(ggbiplot)
library(ggpubr)
library(corrplot)
library(corrr)
library(caret)
library(factoextra)
library(pheatmap)
```

#График ИМТ-траты в plotly (№2)

```{r, message=FALSE, warning=FALSE}

plot_ly(
  data = insurance,
  x = ~ bmi,
  y = ~ charges,
  color = ~ smoker)

```

# А теперь в ggplotly (№3)

```{r}
plot <- insurance %>%
  ggplot(aes(x = bmi, y = charges, color = smoker)) +
  geom_point(size = 1.5) +
  theme_light()

ggplotly(plot)
```

# Корреляционный анализ (№4)

```{r}
insurance_for_cor <- insurance %>%
  select(is.integer | is.numeric)

insurance_cor <- cor(insurance_for_cor)
insurance_cor
```

## Визуализируем матрицу

```{r}
corrplot(insurance_cor, method = "color", order = "alphabet", type = "upper")
```

## И другим способом

```{r}
corrplot.mixed(insurance_cor, lower = "color", upper = "pie", order = "AOE")
```

## И ещё одним

```{r}
insurance_cor %>%
  rplot()
```

# Поработаем с датафреймом (№5)

```{r}
# Сначала отберем все номинативные переменные и превратим их в бинарные

dummy <- dummyVars(" ~ sex + smoker + region", data = insurance)

dummy_insurance <- data.frame(predict(dummy, newdata = insurance))

# И объединим с оставшимися нумерическими переменными из оригинального датафрейма

other_insurance <- insurance %>%
  select("age", "bmi", "children", "charges")

new_insurance <- other_insurance %>% bind_cols(dummy_insurance)

glimpse(new_insurance)
```

# Иерархическая классификация (№6)

```{r, warning=FALSE}
# Стандартизуем значения переменных

insurance_scaled <- scale(new_insurance)
head(insurance_scaled)

# И найдем дистанции

insurance_dist <- dist(insurance_scaled, method = "euclidean")
as.matrix(insurance_dist)[1:6, 1:6]
typeof(insurance_dist)
# Высчитываем дендрограмму

insurance_hc <- hclust(d = insurance_dist, 
                        method = "ward.D2")

# И визуализируем

fviz_dend(insurance_hc, cex = 0.1)

```

# Пробуем строить кластеризацию иначе (№7)

```{r, warning=FALSE}
fviz_dend(insurance_hc, k = 3, 
          cex = 0.1,
          k_colors = c("#FF99FF", "#33FF99", "#00CCFF"),
          color_labels_by_k = TRUE,
          type = "circular"
)

clusters <- cutree(insurance_hc, k = 3)

fviz_cluster(list(data = insurance_scaled, cluster = clusters),
             palette = c("#FF99FF", "#33FF99", "#00CCFF"),
             ellipse.type = "convex", 
             repel = TRUE, 
             show.clust.cent = FALSE, 
             ggtheme = theme_light())
```

# Heatmap + иерархическая кластеризация (№8)

```{r}
pheatmap(insurance_scaled)
```

